### ISSUE TITLE
Use TypeScript

### ISSUE THREAD

**Issue by bnchdrff** [streetcredlabs/categories#26]
As a user of this library, in order to more easily keep track of function inputs and outputs and reduce the occurance of bugs in my own code related to type safety, I want the public API functions in this library to have TypeScript type definitions.

Some case studies:

## https://github.com/streetcredlabs/categories/issues/7

If we make this function polymorphic, we'll want to document how the return type changes based on the function type. This is really awkward to do using jsdoc. Using TypeScript we can be really nice and specific in our implementation:

```typescript
function findById(id: number): Category;
function findById(ids: number[]): Category[];
function findById(
  idOrIds: number | number[]
): Category | Category[] {
  // ...
}
```

## https://github.com/streetcredlabs/categories/issues/4

TypeScript would provide compile-time type checking; this provides a guarantee that, if you're using TS with this library, you won't be allowed to violate the type contracts we set up. We'd still want to do runtime assertions where they're needed, though.

**Comment by tylergaw** [comment]
@bnchdrff I was a big https://www.npmjs.com/package/prop-types user when it was a recommended approach and I find myself missing a lot about it. A big thing being default values for props. Does Typescript have similarities to how prop-types was used?

**Comment by bnchdrff** [comment]
yes! using TS with react supplants proptypes; check out https://www.typescriptlang.org/docs/handbook/jsx.html#stateless-functional-component for some examples

i find that using ts interfaces to define props much friendlier than using prop-types; the interfaces can even be used by other parts of the program.
